language: swift
osx_image: xcode10.3
os: osx
branches:
  only:
  - "/.*/"
cache:
  directories:
  - Carthage
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=HyperwalletSDK.xcodeproj
  - IOS_FRAMEWORK_SCHEME="HyperwalletSDK"
  matrix:
  - ios_version='12.1'  ios_device='iPhone XR' scheme="$IOS_FRAMEWORK_SCHEME"  platform='iOS
    Simulator'
before_install:
- |
  ios_uid=$(xcrun instruments -s devices | grep Simulator | grep "$ios_device ($ios_version)*" | grep -o "[0-9A-F]\{8\}-[0-9A-F]\{4\}-[0-9A-F]\{4\}-[0-9A-F]\{4\}-[0-9A-F]\{12\}")
  xcrun simctl boot $ios_uid
- xcrun simctl list
- brew outdated carthage || brew upgrade carthage
- carthage update --platform iOS  --cache-builds
- gem i slather
- brew outdated swiftlint || brew upgrade swiftlint
- xcrun simctl list | grep "(Booted)"
- swiftlint version
script: |
  set -o pipefail
  set -e
  # Define the destination emulator
  destination="platform=$platform,OS=$ios_version,name=$ios_device"
  # Build and test Framework in Debug
  xcodebuild -enableCodeCoverage YES clean build test -project "$PROJECT" \
    -scheme "$scheme" \
    -destination "$destination" \
    -configuration Debug ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  # Lint - Add `--strict` to fail for warning and violation
  swiftlint lint --strict --reporter json
after_success: slather
notifications:
  slack:
    rooms:
      secure: Tjhsz5fuDkTNp6ieuhsr6yCL3dxsqMnLrE/dM+qK/peXussoAB6dqZn5LsBskVNrTPUsOnr4XFVjUVxLLJqL51UNi4pRcrL016d2CFaJ0AyAwUQ2vHgYtIOvzBImyCjeARqD/fHAcIVOWyAQRUj+EVxFdOz0FzQG5lV8/Ty17KJP1zAd1cgIWkWMpz1Ig9mIu6aYVbk8PGFGKZLLPxsRQC35Dw7nKaOs2AKlTTI/5co525RhS90dRS5MUygLcyDMuvIfIFPzw9lroHlQHdFx3mTrKKrK+5oa/rF/VEZDHjkZe0rnLbz7E6NP0UJ4U2gMJEN1smDRyAVsqYzrUbGFG1eN32AP6TeQz8QmugJWWHVGukC5sDO33vlaHiKCsBxV/CnckxOHCyPyVtUs1piDVGSUZA3zXqcHs75aCEYUBuMPdSVABfts5IhU0W4RSXXhCEZK8F8GhvpEzwCQLb/BNczSSykW/xGB3cNZ64eOeoFzTBT92Vi60GjWxRJVNiwY3qcUUU3bD1P0avSDDa5fBlEXB3VxL5CNayPNGCl9KqOpt02ooRZ062lH9EOTpsxI7Ii09DezX9NcpEHvIVz1nI7oaojf4sBMt+W6PKcHGLCnzkDf/dntSn29/RhlF/uxFF4EPwRUt/fWye1500FU03f4/3grO8u/olOj9/w6UDA=
      on_success: always
      on_failure: always
