language: swift
osx_image: xcode10.3
os: osx
branches:
  only:
  - "/.*/"
cache:
  directories:
  - Carthage
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=HyperwalletSDK.xcodeproj
  - IOS_FRAMEWORK_SCHEME="HyperwalletSDK"
  matrix:
  - ios_version='12.1'  ios_device='iPhone XR' scheme="$IOS_FRAMEWORK_SCHEME"  platform='iOS
    Simulator'
before_install:
- |
  ios_uid=$(xcrun instruments -s devices | grep Simulator | grep "$ios_device ($ios_version)*" | grep -o "[0-9A-F]\{8\}-[0-9A-F]\{4\}-[0-9A-F]\{4\}-[0-9A-F]\{4\}-[0-9A-F]\{12\}")
  xcrun simctl boot $ios_uid
- xcrun simctl list
- brew outdated carthage || brew upgrade carthage
- carthage update --platform iOS  --cache-builds
- gem i slather
- brew outdated swiftlint || brew upgrade swiftlint
- xcrun simctl list | grep "(Booted)"
- swiftlint version
script: |
  set -o pipefail
  set -e
  # Define the destination emulator
  destination="platform=$platform,OS=$ios_version,name=$ios_device"
  # Build and test Framework in Debug
  xcodebuild -enableCodeCoverage YES clean build test -project "$PROJECT" \
    -scheme "$scheme" \
    -destination "$destination" \
    -configuration Debug ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  # Lint - Add `--strict` to fail for warning and violation
  swiftlint lint --strict --reporter json
after_success: slather
notifications:
  slack:
    rooms:
      secure: Q/ItQ9CENK7L1Yz7EOFtn8PDnwgfXLToa8HJT+XMXARWPIO+QZGAugl2heqC4YZdl4q4r9OKUvXCRKrz5cFfDCynUIwG1plQQ8hq4Hmk/jXyFecFQMf/v6IMDgE+JPxaeIYoEzY7M5IytNsFycvgBhBWjiPg4kXS4ZfMY5IHt1tLkbDXWimQnDYdtymbfyg8+hsTOZpcZgPFZK+YqxpzY4vxiSgUqwirKIyEDJ+g/WjsCmNuS8T2sXYhQk6Jz9KYiL6VWo25odMQZMGuyosr8pPp99I7DrE9DP98DuKED2ZJIZyBWTtNqcFh18BlaBn9vgA+QSLgWdPo5LgfQtpaj1u/o0FqahxbuyLYabfnEL1OTFOdbRHV5IyTLQ357jpkpJON1mtnxcBFe3eiX8yyuXBd/ojYQ3FDRn5Bqeyvz4rAEwTVo3Hhjxs3htg1nvUQK+NJ3PlnEnI9fPRkxXmGTQNOCB+8DUjCnLCEi/kTQXOC2Z6t7mjyCFquypdJZuNlIA4NliYPl+oaQWNY6cuIEdX7oXSbWbBRb+sPNzPsmgby0myz9x8zsaSyDi1apAOD+idoNlzWvt3c4jVdGaycSfi/XLlDiquxExDAxZLiVelLJ5NUu6HUoaNmTYcwDKDHnFTjCSyB17/AS53iZonwlx47yg9fqIiwBVJ3HwI2NM0=
      on_success: always
      on_failure: always
