language: swift
osx_image: xcode10.2
os: osx
branches:
  only:
  - "/.*/"
cache:
  directories:
  - Carthage
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=HyperwalletSDK.xcodeproj
  - IOS_FRAMEWORK_SCHEME="HyperwalletSDK"
  matrix:
  - ios_version='12.1'  ios_device='iPhone XR' scheme="$IOS_FRAMEWORK_SCHEME"  platform='iOS
    Simulator'
before_install:
- |
  ios_uid=$(xcrun instruments -s devices | grep Simulator | grep "$ios_device ($ios_version)*" | grep -o "[0-9A-F]\{8\}-[0-9A-F]\{4\}-[0-9A-F]\{4\}-[0-9A-F]\{4\}-[0-9A-F]\{12\}")
  xcrun simctl boot $ios_uid
- xcrun simctl list
- brew outdated carthage || brew upgrade carthage
- carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds
- gem i slather
- brew outdated swiftlint || brew upgrade swiftlint
- xcrun simctl list | grep "(Booted)"
- swiftlint version
script: |
  set -o pipefail
  set -e
  # Define the destination emulator
  destination="platform=$platform,OS=$ios_version,name=$ios_device"
  # Build and test Framework in Debug
  xcodebuild -enableCodeCoverage YES clean build test -project "$PROJECT" \
    -scheme "$scheme" \
    -destination "$destination" \
    -configuration Debug ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  # Lint - Add `--strict` to fail for warning and violation
  swiftlint lint --reporter json
after_success: slather
notifications:
  slack:
    rooms:
      secure: WrrqJ87SicYdLZoPb+8ooZrnnMM7A/KLFya2LIGDMqa3XCRGmvj45uodX9HrdokfqPFeSEW3wBcUvg5e8rXh+ZvsjZtiAHtyrDy+QuB3avsjHYCG/SI7esQn931BamGit0tMnxI/ia52EWBqRe3nbLlgNPkQRwCOPX1ApoSz00MsS1K1VppCdUgPyrVTw6mFMhjI658T8MTdwGvLVLGZl5QhVO0+lxIf1JKCsVyszDuLEEJp1zZylKSTuD05V/GrKPxjD3mkm1u3HbUb88RqYo71g4ZSy3fG4sMRG4XJi0xBb7/R4MZmZqzDbu1bWFiAh6bFAOp4u4haTIGHYk9a+AABj83XCQk6E0e5RZiv7J+9WjDHFCzmt6f+rkOv/A/ThDbUvJGTT7VSBLojCIjLKPpKAOIbOhaqnvWSJ7EktGaxvPSB/GAvFGqIvqSToFuaNkcQpFX3KGXQgQ5qDxOlfxOx5AvI8G0jDC9fmTqE6vVhYrW0c5sC5crnP1P5C3PHwEqC6vC6+4LO+kZX52qBR3nIRhlasgs6WyVBBiHdNRyLjK7G2oC3cQ1hFV+JxMkOrxIrujaQRGPNTZ8a2diFkgBqGaHJ272W4JPPduBA4kA6VjETpnp1nfRAuAEfbbeZhlBRr5ZwHmrdoUg71RwpT3KGgS0/ZiBIibVxYjlZp10=
